alter table public.segments add column if not exists icon_path text;

update public.segments set description = 'Base produtiva diversificada e cadeias consolidadas, com forte integração entre produção agropecuária, agroindústria, tecnologia e acesso aos mercados nacional e internacional.', icon_path = '/sector-icons/01_cadeia_agropecuaria.png' where name = 'Cadeia agropecuária' and segment_type = 'priority';
update public.segments set description = 'Ecossistema industrial consolidado, com montadoras, sistemistas e fornecedores, além de localização estratégica para atender mercados no Brasil e no Mercosul.', icon_path = '/sector-icons/02_cadeia_automotiva.png' where name = 'Cadeia automotiva' and segment_type = 'priority';
update public.segments set description = 'Cadeia produtiva integrada, conectando matérias-primas, química, plásticos e diferentes segmentos da indústria de transformação, com oportunidades para novos investimentos e maior agregação de valor.', icon_path = '/sector-icons/03_cadeia_petroquimica.png' where name = 'Cadeia petroquímica' and segment_type = 'priority';
update public.segments set description = 'Mercado impulsionado pela força da produção agrícola, com demanda relevante por fertilizantes, corretivos, insumos e novas soluções voltadas à produtividade e à eficiência no campo.', icon_path = '/sector-icons/04_fertilizantes.png' where name = 'Fertilizantes' and segment_type = 'priority';
update public.segments set description = 'Tradição industrial associada a uma forte base agropecuária, criando condições favoráveis para produção, inovação e desenvolvimento de máquinas, implementos e tecnologias para o campo.', icon_path = '/sector-icons/05_maquinas_agricolas.png' where name = 'Máquinas agrícolas' and segment_type = 'priority';
update public.segments set description = 'Base industrial diversificada, engenharia qualificada e capacidade tecnológica para desenvolver máquinas, equipamentos, componentes eletrônicos, semicondutores e soluções industriais de maior valor agregado.', icon_path = '/sector-icons/06_maquinas_equipamentos_semicondutores.png' where name = 'Máquinas, equipamentos e semicondutores' and segment_type = 'priority';
update public.segments set description = 'Potencial para expansão de energias renováveis, biocombustíveis, armazenamento, hidrogênio de baixa emissão e novas cadeias industriais relacionadas à transição energética e à descarbonização.', icon_path = '/sector-icons/07_produtos_transicao_energetica.png' where name = 'Produtos de transição energética' and segment_type = 'priority';
update public.segments set description = 'Ecossistema de inovação e capital humano qualificado, com oportunidades em software, inteligência artificial, automação, dados, serviços digitais e soluções tecnológicas para diferentes setores da economia.', icon_path = '/sector-icons/08_produtos_servicos_digitais.png' where name = 'Produtos e serviços digitais' and segment_type = 'priority';
update public.segments set description = 'Produtos com forte identidade territorial e potencial de diferenciação por qualidade e origem, agregando valor a cadeias como alimentos, bebidas e produtos especializados.', icon_path = '/sector-icons/09_produtos_regionais.png' where name = 'Produtos regionais' and segment_type = 'priority';
update public.segments set description = 'Rede de saúde e conhecimento técnico consolidados, com oportunidades em equipamentos médicos, dispositivos, diagnóstico, tecnologia hospitalar e soluções inovadoras para o setor de saúde.', icon_path = '/sector-icons/10_saude_equipamentos_medicos.png' where name = 'Saúde — equipamentos médicos' and segment_type = 'priority';
update public.segments set description = 'Base florestal e cadeia industrial estruturadas, com oportunidades em madeira, celulose, papel, embalagens, biomassa e produtos florestais de maior valor agregado.', icon_path = '/sector-icons/11_silvicultura_papel_celulose.png' where name = 'Silvicultura, papel e celulose' and segment_type = 'priority';
update public.segments set description = 'Diversidade de paisagens, cultura, gastronomia, natureza e eventos, com oportunidades para investimentos em hospedagem, experiências, infraestrutura e novos serviços turísticos.', icon_path = '/sector-icons/12_turismo.png' where name = 'Turismo' and segment_type = 'priority';
